
services:
  app:
    build: .
    ports:
      - "8000:8000"
    tmpfs:
      - /app/var/cache
      - /app/var/log
    volumes:
      - .:/app
      - vendor_data:/app/vendor
    depends_on:
      database:
        condition: service_healthy
      mailer:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8
      MAILER_DSN: smtp://mailer:1025
      MAILER_SENDER_EMAIL: noreply@fruits-veggies.local
      APP_BASE_URL: http://localhost:8000

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025/healthz"]
      timeout: 5s
      retries: 5
      start_period: 10s
###< symfony/mailer ###

volumes:
  database_data:
  vendor_data:
